model, nls_model, sol = bpdn_model(; bounds = true)
test_well_defined(model, nls_model, sol)
test_objectives(model, nls_model)
@test all(sol .≥ 0)
@test has_bounds(model)
@test all(model.meta.lvar .== 0)
@test all(model.meta.uvar .== Inf)
@test has_bounds(nls_model)
@test all(nls_model.meta.lvar .== 0)
@test all(nls_model.meta.uvar .== Inf)
