# Changes here will be overwritten by Copier
AddAllcontributors: true
AddCitationCFF: true
AddCodeOfConduct: true
AddCompatHelperCI: true
AddContributionDocs: true
AddCopierCI: true
AddDependabot: true
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: true
AddGitHubPRTemplate: true
AddGitHubTemplates: true
AddLintCI: true
AddLychee: true
AddMacToCI: true
AddPrecommit: true
AddTagBotCI: true
AddTestCI: true
AddWinToCI: true
Authors: Dominique Orban <dominique.orban@gmail.com>, Robert Baraldi <robertjbaraldi@gmail.com
AutoIncludeTests: true
CheckExplicitImports: true
CodeOfConductContact: dominique.orban@gmail.com
ConfigIndentation: 2
ExplicitImportsChecklist: exclude_all_qualified_accesses_are_public
JuliaIndentation: 2
JuliaMinCIVersion: lts
JuliaMinVersion: ^1.6.0
License: MPL-2.0
LicenseCopyrightHolders: Dominique Orban, Robert Baraldi <robertjbaraldi@gmail.com
MarkdownIndentation: 2
PackageName: RegularizedProblems
PackageOwner: JuliaSmoothOptimizers
PackageUUID: ea076b23-609f-44d2-bb12-a4ae45328278
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 1
StrategyReviewExcluded: false
UseCirrusCI: true
_src_path: /Users/dpo/.julia/packages/BestieTemplate/jdG8v
