name: Comment Breakage

on:
  workflow_run:
    workflows: ["Breakage"]
    types: 
      - completed

jobs:
  comment_pr:
    uses: MaxenceGollier/.github_jso/.github/workflows/CommentBreakage.yml@test-update-comment
