name: Comment Breakage

on:
  workflow_run:
    workflows: ["Breakage"]
    types: 
      - completed

jobs:
  comment-pr:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });

            var fs = require('fs');

            var breakageArtifacts = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name.startsWith("breakage-")
            });

            for (const artifact of breakageArtifacts) {
              var download = await github.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: artifact.id,
                 archive_format: 'zip',
              });

              fs.writeFileSync(`${artifact.name}.zip`, Buffer.from(download.data));
            }